[darkwebscanfindcompromised]
filename = find_compromised.py
chunked = true
python.version = python3

[darkwebscanemailsecurity]
filename = email_security.py
chunked = true
python.version = python3

[darkwebscanwaf]
filename = waf.py
chunked = true
python.version = python3

[darkwebscanosint]
filename = osint.py
chunked = true
python.version = python3

[darkwebscangetcompanies]
filename = user_companies.py
chunked = true
python.version = python3
